import Footer from './components/Footer';
import Navbar from './components/Navbar';
import './global.css';

export const metadata = {
  title: 'Welcome to Job Buddy',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body>
        <div className="layout">
          <Navbar transparent={false} isLoggedIn={true} />
          <main className="content">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
